name: CI

on: [push, pull_request]

jobs:
  linux:
    name: "Linux"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        run: |
           ./autogen.sh
           mkdir build && cd build
           ../configure  --enable-benchmark --enable-coverage --enable-experimental --enable-module-ecdh --enable-module-recovery --enable-module-generator --enable-module-commitment --enable-module-rangeproof --enable-module-bulletproof --enable-module-whitelist
           make all
           ./tests
           ./exhaustive_tests
